services:
  meilisearch:
    image: getmeili/meilisearch:v1.12.0
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/meili_data
    restart: unless-stopped